version: '3.7'

services:
  mysql:
    image: inf23dw2g09/inf23dw2g09recurso:M2db
    container_name: Pokemon_db_M2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - pokemon-network
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: inf23dw2g09/inf23dw2g09recurso:M2app
    depends_on:
      - mysql
    container_name: Pokemon-app_M2
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - pokemon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  react:
    image: inf23dw2g09/inf23dw2g09recurso:M2react
    depends_on:
      - app
    container_name: Pokemon_react_M2
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - pokemon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3006 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  pokemon-network:
