version: '3.7'

services:
  mysql:
    container_name: Pokemon_db_M2
    build:
      context: ./api
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - pokemon-network
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    depends_on:
      - mysql
    container_name: Pokemon_app_M2
    build:
      context: ./api
      dockerfile: ./dockerfile.app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - pokemon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  react:
    container_name: Pokemon_react_M2
    build:
      context: ./pokemon_react
      dockerfile: ./dockerfile.react
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - pokemon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3006 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pokemon-network:
