version: '3.7'

services:
  mysql:
    image: inf23dw2g09/inf23dw2g09recurso:M1db
    container_name: Pokemon_db_M1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - pokemon-network
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    image: inf23dw2g09/inf23dw2g09recurso:M1app
    depends_on:
      - mysql
    container_name: Pokemon_app_M1
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - pokemon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pokemon-network: